export const getAlpacas = async () => {
  return [
    {
      id: 1,
      nro_arete: "H-24",
      edad: "3 años (4 dientes)",
      peso: "46 kg",
      condicion_corporal: "1",
      raza: "huacaya",
      altura_cruz: "87 cm",
      altura_grupa: "90 cm",
      long_cuerpo: "96 cm",
      ancho_grupa: "23 cm",
      perimetro_toracico: "109 cm",
      ancho_cabeza: "12 cm",
      largo_cabeza: "29 cm",
      isquiones: "12 cm",
      orejas: "14 cm",
    },
    {
      id: 2,
      nro_arete: "HC-08",
      edad: "1 año y medio",
      peso: "34 kg",
      condicion_corporal: 2,
      raza: "huacaya",
      altura_cruz: "79 cm",
      altura_grupa: "83 cm",
      long_cuerpo: "74 cm",
      ancho_grupa: "23 cm",
      perimetro_toracico: "78 cm",
      ancho_cabeza: "14 cm",
      largo_cabeza: "24 cm",
      isquiones: "10 cm",
      orejas: "16 cm",
    },
    {
      id: 3,
      nro_arete: "H-09",
      edad: "4 años",
      peso: "56 kg",
      condicion_corporal: 3.5,
      raza: "huacaya",
      altura_cruz: "86 cm",
      altura_grupa: "92 cm",
      long_cuerpo: "84 cm",
      ancho_grupa: "25 cm",
      perimetro_toracico: "101 cm",
      ancho_cabeza: "13 cm",
      largo_cabeza: "33 cm",
      isquiones: "10 cm",
      orejas: "14 cm",
    },
    {
      id: 4,
      nro_arete: "HS-07",
      edad: "3 años",
      peso: "40 kg",
      condicion_corporal: 3,
      raza: "huacaya",
      altura_cruz: "80 cm",
      altura_grupa: "87 cm",
      long_cuerpo: "94 cm",
      ancho_grupa: "24 cm",
      perimetro_toracico: "96 cm",
      ancho_cabeza: "12 cm",
      largo_cabeza: "27 cm",
      isquiones: "7 cm",
      orejas: "14 cm",
    },
  ];
};

export const getAlpacaById = async (id) => {
  const alpacas = await getAlpacas();
  return alpacas.find((alpaca) => alpaca.id === parseInt(id));
};
