export const getAlpacas = async () => {
  return [
    {
      id: 1,
      nro_arete: "H-24",
      edad: "3 años (4 dientes)",
      peso: 46,
      condicion_corporal: 1,
      raza: "Huacaya",
      altura_cruz: 87,
      altura_grupa: 90,
      long_cuerpo: 96,
      ancho_grupa: 23,
      perimetro_toracico: 109,
      ancho_cabeza: 12,
      largo_cabeza: 29,
      isquiones: 12,
      orejas: 14,
      sexo: "hembra",
    },
    {
      id: 2,
      nro_arete: "HC-08",
      edad: "1 año y medio",
      peso: 34,
      condicion_corporal: 2,
      raza: "Huacaya",
      altura_cruz: 79,
      altura_grupa: 83,
      long_cuerpo: 74,
      ancho_grupa: 23,
      perimetro_toracico: 78,
      ancho_cabeza: 14,
      largo_cabeza: 24,
      isquiones: 10,
      orejas: 16,
      sexo: "hembra",
    },
    {
      id: 3,
      nro_arete: "H-09",
      edad: "4 años",
      peso: 56,
      condicion_corporal: 3.5,
      raza: "Huacaya",
      altura_cruz: 86,
      altura_grupa: 92,
      long_cuerpo: 84,
      ancho_grupa: 25,
      perimetro_toracico: 101,
      ancho_cabeza: 13,
      largo_cabeza: 33,
      isquiones: 10,
      orejas: 14,
      sexo: "hembra",
    },
    {
      id: 4,
      nro_arete: "HS-07",
      edad: "3 años",
      peso: 40,
      condicion_corporal: 3,
      raza: "Huacaya",
      altura_cruz: 80,
      altura_grupa: 87,
      long_cuerpo: 94,
      ancho_grupa: 24,
      perimetro_toracico: 96,
      ancho_cabeza: 12,
      largo_cabeza: 27,
      isquiones: 7,
      orejas: 14,
      sexo: "hembra",
    },
    {
      id: 5,
      nro_arete: "MC-08",
      edad: "5 años",
      peso: 36,
      condicion_corporal: 2,
      raza: "Huacaya",
      altura_cruz: 85,
      altura_grupa: 86,
      long_cuerpo: 62,
      ancho_grupa: 26,
      perimetro_toracico: 80,
      ancho_cabeza: 14,
      largo_cabeza: 26,
      isquiones: 9,
      orejas: 10,
      sexo: "hembra",
    },
    {
      id: 6,
      nro_arete: "S-09",
      edad: "7 años",
      peso: 36,
      condicion_corporal: 1,
      raza: "Huacaya",
      altura_cruz: 76,
      altura_grupa: 79,
      long_cuerpo: 74,
      ancho_grupa: 23,
      perimetro_toracico: 90,
      ancho_cabeza: 14,
      largo_cabeza: 25,
      isquiones: 9,
      orejas: 12,
      sexo: "hembra",
    },
    {
      id: 7,
      nro_arete: "MC-07",
      edad: "6 años",
      peso: 34,
      condicion_corporal: 2.5,
      raza: "Huacaya",
      altura_cruz: 75,
      altura_grupa: 78,
      long_cuerpo: 66,
      ancho_grupa: 24,
      perimetro_toracico: 85,
      ancho_cabeza: 13,
      largo_cabeza: 23,
      isquiones: 9,
      orejas: 11,
      sexo: "hembra",
    },
    {
      id: 8,
      nro_arete: "MS-04",
      edad: "8 años",
      peso: 45,
      condicion_corporal: 2,
      raza: "Huacaya",
      altura_cruz: 93,
      altura_grupa: 96,
      long_cuerpo: 84,
      ancho_grupa: 26,
      perimetro_toracico: 96,
      ancho_cabeza: 17,
      largo_cabeza: 30,
      isquiones: 10,
      orejas: 13,
      sexo: "hembra",
    },
    {
      id: 9,
      nro_arete: "H-14",
      edad: "7 años",
      peso: 66,
      condicion_corporal: 4,
      raza: "Huacaya",
      altura_cruz: 86,
      altura_grupa: 96,
      long_cuerpo: 84,
      ancho_grupa: 33,
      perimetro_toracico: 111,
      ancho_cabeza: 14,
      largo_cabeza: 28,
      isquiones: 10,
      orejas: 13,
      sexo: "hembra",
    },
    {
      id: 10,
      nro_arete: "HS-06",
      edad: "7 años",
      peso: 45,
      condicion_corporal: 2,
      raza: "Huacaya",
      altura_cruz: 91,
      altura_grupa: 94,
      long_cuerpo: 80,
      ancho_grupa: 28,
      perimetro_toracico: 90,
      ancho_cabeza: 16,
      largo_cabeza: 28,
      isquiones: 7,
      orejas: 13,
      sexo: "hembra",
    },
    {
      id: 11,
      nro_arete: "S-01",
      edad: "6 años y medio",
      peso: 35,
      condicion_corporal: 1.5,
      raza: "Huacaya",
      altura_cruz: 83,
      altura_grupa: 81,
      long_cuerpo: 80,
      ancho_grupa: 23,
      perimetro_toracico: 84,
      ancho_cabeza: 14,
      largo_cabeza: 26,
      isquiones: 7,
      orejas: 9,
      sexo: "hembra",
    },
    {
      id: 12,
      nro_arete: "HS-08",
      edad: "5 años",
      peso: 43,
      condicion_corporal: 3,
      raza: "Huacaya",
      altura_cruz: 84,
      altura_grupa: 81,
      long_cuerpo: 78,
      ancho_grupa: 23,
      perimetro_toracico: 86,
      ancho_cabeza: 16,
      largo_cabeza: 30,
      isquiones: 10,
      orejas: 11,
      sexo: "hembra",
    },
    {
      id: 13,
      nro_arete: "S-03",
      edad: "6 años",
      peso: 56,
      condicion_corporal: 3.5,
      raza: "Huacaya",
      altura_cruz: 85,
      altura_grupa: 87,
      long_cuerpo: 81,
      ancho_grupa: 24,
      perimetro_toracico: 91,
      ancho_cabeza: 16,
      largo_cabeza: 32,
      isquiones: 10,
      orejas: 12,
      sexo: "hembra",
    },
    {
      id: 14,
      nro_arete: "HC-1",
      edad: "5 años",
      peso: 36,
      condicion_corporal: 3,
      raza: "Huacaya",
      altura_cruz: 87,
      altura_grupa: 91,
      long_cuerpo: 81,
      ancho_grupa: 25,
      perimetro_toracico: 95,
      ancho_cabeza: 11,
      largo_cabeza: 29,
      isquiones: 11,
      orejas: 16,
      sexo: "hembra",
    },
    {
      id: 15,
      nro_arete: "H-12",
      edad: "4 años y medio",
      peso: 79,
      condicion_corporal: 3.5,
      raza: "Huacaya",
      altura_cruz: 90,
      altura_grupa: 90,
      long_cuerpo: 90,
      ancho_grupa: 34,
      perimetro_toracico: 104.5,
      ancho_cabeza: 17,
      largo_cabeza: 34,
      isquiones: 10,
      orejas: 13,
      sexo: "hembra",
    },
    {
      id: 16,
      nro_arete: "HS-03",
      edad: "3 años y medio",
      peso: 39,
      condicion_corporal: 4,
      raza: "Huacaya",
      altura_cruz: 79,
      altura_grupa: 81,
      long_cuerpo: 75,
      ancho_grupa: 25,
      perimetro_toracico: 88,
      ancho_cabeza: 18,
      largo_cabeza: 33,
      isquiones: 9,
      orejas: 14,
      sexo: "hembra",
    },
    {
      id: 17,
      nro_arete: "HC-10",
      edad: "2 años",
      peso: 27,
      condicion_corporal: 2.5,
      raza: "Huacaya",
      altura_cruz: 77,
      altura_grupa: 80,
      long_cuerpo: 65,
      ancho_grupa: 24,
      perimetro_toracico: 72,
      ancho_cabeza: 15,
      largo_cabeza: 25,
      isquiones: 10,
      orejas: 17,
      sexo: "hembra",
    },
    {
      id: 18,
      nro_arete: "HC-08",
      edad: "3 años",
      peso: 34,
      condicion_corporal: 3.5,
      raza: "Huacaya",
      altura_cruz: 78,
      altura_grupa: 84,
      long_cuerpo: 73,
      ancho_grupa: 25,
      perimetro_toracico: 75,
      ancho_cabeza: 16,
      largo_cabeza: 28,
      isquiones: 10.5,
      orejas: 16,
      sexo: "hembra",
    },
    {
      id: 19,
      nro_arete: "HS-02",
      edad: "6 años y medio",
      peso: 45,
      condicion_corporal: 3.5,
      raza: "Huarizo",
      altura_cruz: 92,
      altura_grupa: 95,
      long_cuerpo: 89,
      ancho_grupa: 28,
      perimetro_toracico: 102,
      ancho_cabeza: 15,
      largo_cabeza: 33,
      isquiones: 11,
      orejas: 15,
      sexo: "hembra",
    },
    {
      id: 20,
      nro_arete: "Sin número",
      edad: "5 años",
      peso: 53,
      condicion_corporal: 2,
      raza: "Huacaya",
      altura_cruz: 85,
      altura_grupa: 91,
      long_cuerpo: 88,
      ancho_grupa: 27,
      perimetro_toracico: 97,
      ancho_cabeza: 16,
      largo_cabeza: 31,
      isquiones: 10,
      orejas: 15,
      sexo: "hembra",
    },
    {
      id: 21,
      nro_arete: "E-9H",
      edad: "3.5 años",
      peso: 45,
      condicion_corporal: 3.5,
      raza: "Huacaya",
      altura_cruz: 88,
      altura_grupa: 91,
      long_cuerpo: 86,
      ancho_grupa: 25,
      perimetro_toracico: 90,
      ancho_cabeza: 15,
      largo_cabeza: 32,
      isquiones: 7.5,
      orejas: 13,
      sexo: "hembra",
    },
    {
      id: 22,
      nro_arete: "S-05",
      edad: "7 años y medio",
      peso: 40,
      condicion_corporal: 3,
      raza: "Huacaya",
      altura_cruz: 70,
      altura_grupa: 80,
      long_cuerpo: 78,
      ancho_grupa: 26,
      perimetro_toracico: 78,
      ancho_cabeza: 14,
      largo_cabeza: 28,
      isquiones: 12,
      orejas: 14.5,
      sexo: "hembra",
    },
    {
      id: 23,
      nro_arete: "E-5H",
      edad: "5 años",
      peso: 58,
      condicion_corporal: 3.2,
      raza: "Huacaya",
      altura_cruz: 72,
      altura_grupa: 87,
      long_cuerpo: 87,
      ancho_grupa: 26,
      perimetro_toracico: 88,
      ancho_cabeza: 13,
      largo_cabeza: 22,
      isquiones: 10,
      orejas: 11.5,
      sexo: "hembra",
    },
    {
      id: 24,
      nro_arete: "HS-10",
      edad: "2 años",
      peso: 42,
      condicion_corporal: 3,
      raza: "Huacaya",
      altura_cruz: 86,
      altura_grupa: 89,
      long_cuerpo: 77,
      ancho_grupa: 26,
      perimetro_toracico: 94,
      ancho_cabeza: 14,
      largo_cabeza: 30,
      isquiones: 10,
      orejas: 12,
      sexo: "hembra",
    },
    {
      id: 25,
      nro_arete: "H-22",
      edad: "6 años",
      peso: 55,
      condicion_corporal: 3,
      raza: "Huacaya",
      altura_cruz: 85,
      altura_grupa: 88,
      long_cuerpo: 74,
      ancho_grupa: 32,
      perimetro_toracico: 96,
      ancho_cabeza: 13,
      largo_cabeza: 28,
      isquiones: 10,
      orejas: 12,
      sexo: "hembra",
    },
    {
      id: 26,
      nro_arete: "HC-04",
      edad: "8 años",
      peso: 46,
      condicion_corporal: 3.5,
      raza: "Huacaya",
      altura_cruz: 77,
      altura_grupa: 77,
      long_cuerpo: 72,
      ancho_grupa: 23,
      perimetro_toracico: 88,
      ancho_cabeza: 28,
      largo_cabeza: 28,
      isquiones: 7,
      orejas: 14,
      sexo: "hembra",
    },
    {
      id: 27,
      nro_arete: "HS-01",
      edad: "6 años",
      peso: 40,
      condicion_corporal: 2.5,
      raza: "Huacaya",
      altura_cruz: 77,
      altura_grupa: 80,
      long_cuerpo: 87,
      ancho_grupa: 26,
      perimetro_toracico: 87,
      ancho_cabeza: 14,
      largo_cabeza: 27,
      isquiones: 7,
      orejas: 14,
      sexo: "hembra",
    },
    {
      id: 28,
      nro_arete: "S-03",
      edad: "5 años",
      peso: 56,
      condicion_corporal: 3,
      raza: "Huacaya",
      altura_cruz: 85,
      altura_grupa: 86,
      long_cuerpo: 88,
      ancho_grupa: 26,
      perimetro_toracico: 91,
      ancho_cabeza: 11,
      largo_cabeza: 29,
      isquiones: 9,
      orejas: 14,
      sexo: "hembra",
    },
    {
      id: 29,
      nro_arete: "HC-07",
      edad: "3 años y medio",
      peso: 43,
      condicion_corporal: 3.5,
      raza: "Huacaya",
      altura_cruz: 86,
      altura_grupa: 88,
      long_cuerpo: 72,
      ancho_grupa: 23,
      perimetro_toracico: 89,
      ancho_cabeza: 14,
      largo_cabeza: 26,
      isquiones: 8,
      orejas: 11,
      sexo: "hembra",
    },
    {
      id: 30,
      nro_arete: "HS-12",
      edad: "2 años",
      peso: 18,
      condicion_corporal: 2.5,
      raza: "Huacaya",
      altura_cruz: 74,
      altura_grupa: 76,
      long_cuerpo: 63,
      ancho_grupa: 20,
      perimetro_toracico: 77,
      ancho_cabeza: 14,
      largo_cabeza: 26,
      isquiones: 5.5,
      orejas: 8,
      sexo: "hembra",
    },
    {
      id: 31,
      nro_arete: "HS-05",
      edad: "5 años",
      peso: 42,
      condicion_corporal: 3.5,
      raza: "Huacaya",
      altura_cruz: 93,
      altura_grupa: 90,
      long_cuerpo: 78,
      ancho_grupa: 24,
      perimetro_toracico: 90,
      ancho_cabeza: 13,
      largo_cabeza: 27,
      isquiones: 9,
      orejas: 13,
      sexo: "hembra",
    },
    {
      id: 32,
      nro_arete: "HS-09",
      edad: "4 años",
      peso: 37,
      condicion_corporal: 1.5,
      raza: "Huacaya",
      altura_cruz: 92,
      altura_grupa: 85,
      long_cuerpo: 83,
      ancho_grupa: 25,
      perimetro_toracico: 87,
      ancho_cabeza: 15,
      largo_cabeza: 29,
      isquiones: 10,
      orejas: 11,
      sexo: "hembra",
    },
    {
      id: 33,
      nro_arete: "H-06",
      edad: "4 años",
      peso: 43,
      condicion_corporal: 3.5,
      raza: "Huacaya",
      altura_cruz: 84,
      altura_grupa: 89,
      long_cuerpo: 97,
      ancho_grupa: 27,
      perimetro_toracico: 110,
      ancho_cabeza: 16,
      largo_cabeza: 31,
      isquiones: 9,
      orejas: 13,
      sexo: "hembra",
    },
    {
      id: 34,
      nro_arete: "S-01",
      edad: "5 años",
      peso: 45,
      condicion_corporal: 4.5,
      raza: "Huacaya",
      altura_cruz: 83,
      altura_grupa: 85,
      long_cuerpo: 71,
      ancho_grupa: 31,
      perimetro_toracico: 94,
      ancho_cabeza: 12,
      largo_cabeza: 26,
      isquiones: null,
      orejas: 12,
      sexo: "macho",
    },
    {
      id: 35,
      nro_arete: "M-06",
      edad: "5 a 7 años",
      peso: 55,
      condicion_corporal: 4.0,
      raza: "Huacaya",
      altura_cruz: 85,
      altura_grupa: 87,
      long_cuerpo: 73,
      ancho_grupa: 33,
      perimetro_toracico: 84,
      ancho_cabeza: 14,
      largo_cabeza: 29,
      isquiones: null,
      orejas: 12,
      sexo: "macho",
    },
    {
      id: 36,
      nro_arete: "S-03",
      edad: "5 a 7 años",
      peso: 41,
      condicion_corporal: 3.5,
      raza: "Huacaya",
      altura_cruz: 83,
      altura_grupa: 85,
      long_cuerpo: 81,
      ancho_grupa: 25.5,
      perimetro_toracico: 90,
      ancho_cabeza: 13,
      largo_cabeza: 26.5,
      isquiones: null,
      orejas: 13,
      sexo: "macho",
    },
    {
      id: 37,
      nro_arete: "S-06",
      edad: "5 años",
      peso: 53,
      condicion_corporal: 4.0,
      raza: "Huacaya - Suri",
      altura_cruz: 81,
      altura_grupa: 87,
      long_cuerpo: 82,
      ancho_grupa: 24.5,
      perimetro_toracico: 97,
      ancho_cabeza: 14,
      largo_cabeza: 29,
      isquiones: null,
      orejas: 13,
      sexo: "macho",
    },
    {
      id: 38,
      nro_arete: "MC-03",
      edad: "5 años",
      peso: 48,
      condicion_corporal: 3.5,
      raza: "Huacaya",
      altura_cruz: 77,
      altura_grupa: 79,
      long_cuerpo: 80,
      ancho_grupa: 21,
      perimetro_toracico: 94,
      ancho_cabeza: 14,
      largo_cabeza: 27,
      isquiones: null,
      orejas: 12,
      sexo: "macho",
    },
    {
      id: 39,
      nro_arete: "M-05",
      edad: "5 a 7 años",
      peso: 56,
      condicion_corporal: 2.5,
      raza: "Huacaya",
      altura_cruz: 81,
      altura_grupa: 83,
      long_cuerpo: 81,
      ancho_grupa: 25,
      perimetro_toracico: 102,
      ancho_cabeza: 15,
      largo_cabeza: 33,
      isquiones: null,
      orejas: 14,
      sexo: "macho",
    },
    {
      id: 40,
      nro_arete: "S-07",
      edad: "5 años",
      peso: 56,
      condicion_corporal: 4.0,
      raza: "Huacaya",
      altura_cruz: 85,
      altura_grupa: 87,
      long_cuerpo: 87,
      ancho_grupa: 24,
      perimetro_toracico: 103,
      ancho_cabeza: 14,
      largo_cabeza: 31,
      isquiones: null,
      orejas: 14,
      sexo: "macho",
    },
    {
      id: 41,
      nro_arete: "H2M",
      edad: "4 a 5 años",
      peso: 48,
      condicion_corporal: 3.0,
      raza: "Huacaya",
      altura_cruz: 83,
      altura_grupa: 85,
      long_cuerpo: 85,
      ancho_grupa: 22,
      perimetro_toracico: 89,
      ancho_cabeza: 14.3,
      largo_cabeza: 26,
      isquiones: null,
      orejas: 14,
      sexo: "macho",
    },
    {
      id: 42,
      nro_arete: "M-17",
      edad: "5 a 6 años",
      peso: 55,
      condicion_corporal: 3.5,
      raza: "Huacaya",
      altura_cruz: 87,
      altura_grupa: 90,
      long_cuerpo: 81.5,
      ancho_grupa: 29.5,
      perimetro_toracico: 104,
      ancho_cabeza: 14,
      largo_cabeza: 31,
      isquiones: null,
      orejas: 13,
      sexo: "macho",
    },
    {
      id: 43,
      nro_arete: "H1M",
      edad: "5 a 7 años",
      peso: 58,
      condicion_corporal: 3.0,
      raza: "Huacaya",
      altura_cruz: 87,
      altura_grupa: 88,
      long_cuerpo: 82,
      ancho_grupa: 21,
      perimetro_toracico: 103,
      ancho_cabeza: 13,
      largo_cabeza: 26,
      isquiones: null,
      orejas: 14,
      sexo: "macho",
    },
    {
      id: 44,
      nro_arete: "S-02",
      edad: "5 a 7 años",
      peso: 43,
      condicion_corporal: 4.0,
      raza: "Huacaya",
      altura_cruz: 83,
      altura_grupa: 88,
      long_cuerpo: 83,
      ancho_grupa: 27,
      perimetro_toracico: 85,
      ancho_cabeza: 14,
      largo_cabeza: 23,
      isquiones: null,
      orejas: 14,
      sexo: "macho",
    },
    {
      id: 45,
      nro_arete: "S-09",
      edad: "5 a 7 años",
      peso: 54,
      condicion_corporal: 4.5,
      raza: "Huacaya - Suri",
      altura_cruz: 81,
      altura_grupa: 83,
      long_cuerpo: 89,
      ancho_grupa: 27,
      perimetro_toracico: 98.5,
      ancho_cabeza: 12,
      largo_cabeza: 30,
      isquiones: null,
      orejas: 13,
      sexo: "macho",
    },
    {
      id: 46,
      nro_arete: "S-04",
      edad: "5 a 7 años",
      peso: 41,
      condicion_corporal: 3.5,
      raza: "Huacaya",
      altura_cruz: 79,
      altura_grupa: 81.5,
      long_cuerpo: 76.5,
      ancho_grupa: 25,
      perimetro_toracico: 92,
      ancho_cabeza: 14,
      largo_cabeza: 26,
      isquiones: null,
      orejas: 14,
      sexo: "macho",
    },
  ];
};

export const getAlpacaById = async (id) => {
  const alpacas = await getAlpacas();
  return alpacas.find((alpaca) => alpaca.id === parseInt(id));
};
