export const getAlpacas = async () => {
  return [
    {
      id: 1,
      nro_arete: "H-24",
      edad: "3 años (4 dientes)",
      peso: "46 kg",
      condicion_corporal: "1",
      raza: "huacaya",
      altura_cruz: "87 cm",
      altura_grupa: "90 cm",
      long_cuerpo: "96 cm",
      ancho_grupa: "23 cm",
      perimetro_toracico: "109 cm",
      ancho_cabeza: "12 cm",
      largo_cabeza: "29 cm",
      isquiones: "12 cm",
      orejas: "14 cm",
    },
    {
      id: 2,
      nro_arete: "HC-08",
      edad: "1 año y medio",
      peso: "34 kg",
      condicion_corporal: 2,
      raza: "huacaya",
      altura_cruz: "79 cm",
      altura_grupa: "83 cm",
      long_cuerpo: "74 cm",
      ancho_grupa: "23 cm",
      perimetro_toracico: "78 cm",
      ancho_cabeza: "14 cm",
      largo_cabeza: "24 cm",
      isquiones: "10 cm",
      orejas: "16 cm",
    },
    {
      id: 3,
      nro_arete: "H-09",
      edad: "4 años",
      peso: "56 kg",
      condicion_corporal: 3.5,
      raza: "huacaya",
      altura_cruz: "86 cm",
      altura_grupa: "92 cm",
      long_cuerpo: "84 cm",
      ancho_grupa: "25 cm",
      perimetro_toracico: "101 cm",
      ancho_cabeza: "13 cm",
      largo_cabeza: "33 cm",
      isquiones: "10 cm",
      orejas: "14 cm",
    },
    {
      id: 4,
      nro_arete: "HS-07",
      edad: "3 años",
      peso: "40 kg",
      condicion_corporal: 3,
      raza: "huacaya",
      altura_cruz: "80 cm",
      altura_grupa: "87 cm",
      long_cuerpo: "94 cm",
      ancho_grupa: "24 cm",
      perimetro_toracico: "96 cm",
      ancho_cabeza: "12 cm",
      largo_cabeza: "27 cm",
      isquiones: "7 cm",
      orejas: "14 cm",
    },
    {
      id: 5,
      nro_arete: "MC-08",
      edad: "5 años",
      peso: "36 kg",
      condicion_corporal: "2",
      raza: "huacaya",
      altura_cruz: "85 cm",
      altura_grupa: "86 cm",
      long_cuerpo: "62 cm",
      ancho_grupa: "26 cm",
      perimetro_toracico: "80 cm",
      ancho_cabeza: "14 cm",
      largo_cabeza: "26 cm",
      isquiones: "9 cm",
      orejas: "10 cm",
    },
    {
      id: 6,
      nro_arete: "S-09",
      edad: "7 años",
      peso: "36 kg",
      condicion_corporal: "1",
      raza: "huacaya",
      altura_cruz: "76 cm",
      altura_grupa: "79 cm",
      long_cuerpo: "74 cm",
      ancho_grupa: "23 cm",
      perimetro_toracico: "90 cm",
      ancho_cabeza: "14 cm",
      largo_cabeza: "25 cm",
      isquiones: "9 cm",
      orejas: "12 cm",
    },
    {
      id: 7,
      nro_arete: "MC-07",
      edad: "6 años",
      peso: "34 kg",
      condicion_corporal: "2.5",
      raza: "huacaya",
      altura_cruz: "75 cm",
      altura_grupa: "78 cm",
      long_cuerpo: "66 cm",
      ancho_grupa: "24 cm",
      perimetro_toracico: "85 cm",
      ancho_cabeza: "13 cm",
      largo_cabeza: "23 cm",
      isquiones: "9 cm",
      orejas: "11 cm",
    },
    {
      id: 8,
      nro_arete: "MS-04",
      edad: "8 años",
      peso: "45 kg",
      condicion_corporal: "2",
      raza: "huacaya",
      altura_cruz: "93 cm",
      altura_grupa: "96 cm",
      long_cuerpo: "84 cm",
      ancho_grupa: "26 cm",
      perimetro_toracico: "96 cm",
      ancho_cabeza: "17 cm",
      largo_cabeza: "30 cm",
      isquiones: "10 cm",
      orejas: "13 cm",
    },
    {
      id: 9,
      nro_arete: "H-14",
      edad: "7 años",
      peso: "66 kg",
      condicion_corporal: "4",
      raza: "huacaya",
      altura_cruz: "86 cm",
      altura_grupa: "96 cm",
      long_cuerpo: "84 cm",
      ancho_grupa: "33 cm",
      perimetro_toracico: "111 cm",
      ancho_cabeza: "14 cm",
      largo_cabeza: "28 cm",
      isquiones: "10 cm",
      orejas: "13 cm",
    },
    {
      id: 10,
      nro_arete: "HS-06",
      edad: "7 años",
      peso: "45 kg",
      condicion_corporal: "2",
      raza: "huacaya",
      altura_cruz: "91 cm",
      altura_grupa: "94 cm",
      long_cuerpo: "80 cm",
      ancho_grupa: "28 cm",
      perimetro_toracico: "90 cm",
      ancho_cabeza: "16 cm",
      largo_cabeza: "28 cm",
      isquiones: "7 cm",
      orejas: "13 cm",
    },
    {
      id: 11,
      nro_arete: "S-01",
      edad: "6 años y medio",
      peso: "35 kg",
      condicion_corporal: "1.5",
      raza: "huacaya",
      altura_cruz: "83 cm",
      altura_grupa: "81 cm",
      long_cuerpo: "80 cm",
      ancho_grupa: "23 cm",
      perimetro_toracico: "84 cm",
      ancho_cabeza: "14 cm",
      largo_cabeza: "26 cm",
      isquiones: "7 cm",
      orejas: "9 cm",
    },
    {
      id: 12,
      nro_arete: "HS-08",
      edad: "5 años",
      peso: "43 kg",
      condicion_corporal: "3",
      raza: "huacaya",
      altura_cruz: "84 cm",
      altura_grupa: "81 cm",
      long_cuerpo: "78 cm",
      ancho_grupa: "23 cm",
      perimetro_toracico: "86 cm",
      ancho_cabeza: "16 cm",
      largo_cabeza: "30 cm",
      isquiones: "10 cm",
      orejas: "11 cm",
    },
    {
      id: 13,
      nro_arete: "S-03",
      edad: "6 años",
      peso: "56 kg",
      condicion_corporal: "3.5",
      raza: "huacaya",
      altura_cruz: "85 cm",
      altura_grupa: "87 cm",
      long_cuerpo: "81 cm",
      ancho_grupa: "24 cm",
      perimetro_toracico: "91 cm",
      ancho_cabeza: "16 cm",
      largo_cabeza: "32 cm",
      isquiones: "10 cm",
      orejas: "12 cm",
    },
    {
      id: 14,
      nro_arete: "HC-1",
      edad: "5 años",
      peso: "36 kg",
      condicion_corporal: "3",
      raza: "huacaya",
      altura_cruz: "87 cm",
      altura_grupa: "91 cm",
      long_cuerpo: "81 cm",
      ancho_grupa: "25 cm",
      perimetro_toracico: "95 cm",
      ancho_cabeza: "11 cm",
      largo_cabeza: "29 cm",
      isquiones: "11 cm",
      orejas: "16 cm",
    },
    {
      id: 15,
      nro_arete: "H-12",
      edad: "4 años y medio",
      peso: "79 kg",
      condicion_corporal: "3.5",
      raza: "huacaya",
      altura_cruz: "90 cm",
      altura_grupa: "90 cm",
      long_cuerpo: "90 cm",
      ancho_grupa: "34 cm",
      perimetro_toracico: "104.5 cm",
      ancho_cabeza: "17 cm",
      largo_cabeza: "34 cm",
      isquiones: "10 cm",
      orejas: "13 cm",
    },
    {
      id: 16,
      nro_arete: "HS-03",
      edad: "3 años y medio",
      peso: "39 kg",
      condicion_corporal: 4,
      raza: "huacaya",
      altura_cruz: "79 cm",
      altura_grupa: "81 cm",
      long_cuerpo: "75 cm",
      ancho_grupa: "25 cm",
      perimetro_toracico: "88 cm",
      ancho_cabeza: "18 cm",
      largo_cabeza: "33 cm",
      isquiones: "9 cm",
      orejas: "14 cm",
    },
    {
      id: 17,
      nro_arete: "HC-10",
      edad: "2 años",
      peso: "27 kg",
      condicion_corporal: 2.5,
      raza: "huacaya",
      altura_cruz: "77 cm",
      altura_grupa: "80 cm",
      long_cuerpo: "65 cm",
      ancho_grupa: "24 cm",
      perimetro_toracico: "72 cm",
      ancho_cabeza: "15 cm",
      largo_cabeza: "25 cm",
      isquiones: "10 cm",
      orejas: "17 cm",
    },
    {
      id: 18,
      nro_arete: "HC-08",
      edad: "3 años",
      peso: "34 kg",
      condicion_corporal: 3.5,
      raza: "huacaya",
      altura_cruz: "78 cm",
      altura_grupa: "84 cm",
      long_cuerpo: "73 cm",
      ancho_grupa: "25 cm",
      perimetro_toracico: "75 cm",
      ancho_cabeza: "16 cm",
      largo_cabeza: "28 cm",
      isquiones: "10.5 cm",
      orejas: "16 cm",
    },
    {
      id: 19,
      nro_arete: "HS-02",
      edad: "6 años y medio",
      peso: "45 kg",
      condicion_corporal: 3.5,
      raza: "huarizo",
      altura_cruz: "92 cm",
      altura_grupa: "95 cm",
      long_cuerpo: "89 cm",
      ancho_grupa: "28 cm",
      perimetro_toracico: "102 cm",
      ancho_cabeza: "15 cm",
      largo_cabeza: "33 cm",
      isquiones: "11 cm",
      orejas: "15 cm",
    },
    {
      id: 20,
      nro_arete: "Sin número",
      edad: "5 años",
      peso: "53 kg",
      condicion_corporal: 2,
      raza: "huacaya",
      altura_cruz: "85 cm",
      altura_grupa: "91 cm",
      long_cuerpo: "88 cm",
      ancho_grupa: "27 cm",
      perimetro_toracico: "97 cm",
      ancho_cabeza: "16 cm",
      largo_cabeza: "31 cm",
      isquiones: "10 cm",
      orejas: "15 cm",
    },
    {
      id: 21,
      nro_arete: "E-9H",
      edad: "3.5 años",
      peso: "45 kg",
      condicion_corporal: 3.5,
      raza: "huacaya",
      altura_cruz: "88 cm",
      altura_grupa: "91 cm",
      long_cuerpo: "86 cm",
      ancho_grupa: "25 cm",
      perimetro_toracico: "90 cm",
      ancho_cabeza: "15 cm",
      largo_cabeza: "32 cm",
      isquiones: "7.5 cm",
      orejas: "13 cm",
    },
    {
      id: 22,
      nro_arete: "S-05",
      edad: "7 años y medio",
      peso: "40 kg",
      condicion_corporal: 3,
      raza: "huacaya",
      altura_cruz: "70 cm",
      altura_grupa: "80 cm",
      long_cuerpo: "78 cm",
      ancho_grupa: "26 cm",
      perimetro_toracico: "78 cm",
      ancho_cabeza: "14 cm",
      largo_cabeza: "28 cm",
      isquiones: "12 cm",
      orejas: "14.5 cm",
    },
    {
      id: 23,
      nro_arete: "E-5H",
      edad: "5 años",
      peso: "58 kg",
      condicion_corporal: 3.2,
      raza: "huacaya",
      altura_cruz: "72 cm",
      altura_grupa: "87 cm",
      long_cuerpo: "87 cm",
      ancho_grupa: "26 cm",
      perimetro_toracico: "88 cm",
      ancho_cabeza: "13 cm",
      largo_cabeza: "22 cm",
      isquiones: "10 cm",
      orejas: "11.5 cm",
    },
    {
      id: 24,
      nro_arete: "HS-10",
      edad: "2 años",
      peso: "42 kg",
      condicion_corporal: 3,
      raza: "huacaya",
      altura_cruz: "86 cm",
      altura_grupa: "89 cm",
      long_cuerpo: "77 cm",
      ancho_grupa: "26 cm",
      perimetro_toracico: "94 cm",
      ancho_cabeza: "14 cm",
      largo_cabeza: "30 cm",
      isquiones: "10 cm",
      orejas: "12 cm",
    },
    {
      id: 25,
      nro_arete: "H-22",
      edad: "6 años",
      peso: "55 kg",
      condicion_corporal: 3,
      raza: "huacaya",
      altura_cruz: "85 cm",
      altura_grupa: "88 cm",
      long_cuerpo: "74 cm",
      ancho_grupa: "32 cm",
      perimetro_toracico: "96 cm",
      ancho_cabeza: "13 cm",
      largo_cabeza: "28 cm",
      isquiones: "10 cm",
      orejas: "12 cm",
    },
    {
      id: 26,
      nro_arete: "HC-04",
      edad: "8 años",
      peso: "46 kg",
      condicion_corporal: 3.5,
      raza: "huacaya",
      altura_cruz: "77 cm",
      altura_grupa: "77 cm",
      long_cuerpo: "72 cm",
      ancho_grupa: "23 cm",
      perimetro_toracico: "88 cm",
      ancho_cabeza: "28 cm",
      largo_cabeza: "28 cm",
      isquiones: "7 cm",
      orejas: "14 cm",
    },
    {
      id: 27,
      nro_arete: "HS-01",
      edad: "6 años",
      peso: "40 kg",
      condicion_corporal: 2.5,
      raza: "huacaya",
      altura_cruz: "77 cm",
      altura_grupa: "80 cm",
      long_cuerpo: "87 cm",
      ancho_grupa: "26 cm",
      perimetro_toracico: "87 cm",
      ancho_cabeza: "14 cm",
      largo_cabeza: "27 cm",
      isquiones: "7 cm",
      orejas: "14 cm",
    },
    {
      id: 28,
      nro_arete: "S-03",
      edad: "5 años",
      peso: "56 kg",
      condicion_corporal: 3,
      raza: "huacaya",
      altura_cruz: "85 cm",
      altura_grupa: "86 cm",
      long_cuerpo: "88 cm",
      ancho_grupa: "26 cm",
      perimetro_toracico: "91 cm",
      ancho_cabeza: "11 cm",
      largo_cabeza: "29 cm",
      isquiones: "9 cm",
      orejas: "14 cm",
    },
    {
      id: 29,
      nro_arete: "HC-07",
      edad: "3 años y medio",
      peso: "43 kg",
      condicion_corporal: 3.5,
      raza: "huacaya",
      altura_cruz: "86 cm",
      altura_grupa: "88 cm",
      long_cuerpo: "72 cm",
      ancho_grupa: "23 cm",
      perimetro_toracico: "89 cm",
      ancho_cabeza: "14 cm",
      largo_cabeza: "26 cm",
      isquiones: "8 cm",
      orejas: "11 cm",
    },
    {
      id: 30,
      nro_arete: "HS-12",
      edad: "2 años",
      peso: "18 kg",
      condicion_corporal: 2.5,
      raza: "huacaya",
      altura_cruz: "74 cm",
      altura_grupa: "76 cm",
      long_cuerpo: "63 cm",
      ancho_grupa: "20 cm",
      perimetro_toracico: "77 cm",
      ancho_cabeza: "14 cm",
      largo_cabeza: "26 cm",
      isquiones: "5.5 cm",
      orejas: "8 cm",
    },
    {
      id: 31,
      nro_arete: "HS-05",
      edad: "5 años",
      peso: "42 kg",
      condicion_corporal: 3.5,
      raza: "huacaya",
      altura_cruz: "93 cm",
      altura_grupa: "90 cm",
      long_cuerpo: "78 cm",
      ancho_grupa: "24 cm",
      perimetro_toracico: "90 cm",
      ancho_cabeza: "13 cm",
      largo_cabeza: "27 cm",
      isquiones: "9 cm",
      orejas: "13 cm",
    },
    {
      id: 32,
      nro_arete: "HS-09",
      edad: "4 años",
      peso: "37 kg",
      condicion_corporal: 1.5,
      raza: "huacaya",
      altura_cruz: "92 cm",
      altura_grupa: "85 cm",
      long_cuerpo: "83 cm",
      ancho_grupa: "25 cm",
      perimetro_toracico: "87 cm",
      ancho_cabeza: "15 cm",
      largo_cabeza: "29 cm",
      isquiones: "10 cm",
      orejas: "11 cm",
    },
    {
      id: 33,
      nro_arete: "H-06",
      edad: "4 años",
      peso: "43 kg",
      condicion_corporal: 3.5,
      raza: "huacaya",
      altura_cruz: "84 cm",
      altura_grupa: "89 cm",
      long_cuerpo: "97 cm",
      ancho_grupa: "27 cm",
      perimetro_toracico: "110 cm",
      ancho_cabeza: "16 cm",
      largo_cabeza: "31 cm",
      isquiones: "9 cm",
      orejas: "13 cm",
    },
  ];
};

export const getAlpacaById = async (id) => {
  const alpacas = await getAlpacas();
  return alpacas.find((alpaca) => alpaca.id === parseInt(id));
};
